# Generated by Django 5.1 on 2025-11-19 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_GameVerse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='carrito',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
