# Generated by Django 5.1 on 2025-11-27 14:46

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_GameVerse', '0002_usuario_carrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='credito',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
